// Code generated by vitrum gencmd. DO NOT EDIT.

package std

import (
	"fmt"
	vit "github.com/omniskop/vitrum/vit"
)

type Column struct {
	Item
	id string

	topPadding    vit.OptionalValue[*vit.FloatValue]
	rightPadding  vit.OptionalValue[*vit.FloatValue]
	bottomPadding vit.OptionalValue[*vit.FloatValue]
	leftPadding   vit.OptionalValue[*vit.FloatValue]
	padding       vit.FloatValue
	spacing       vit.FloatValue
	childLayouts  vit.LayoutList
}

func NewColumn(id string, scope vit.ComponentContainer) *Column {
	return &Column{
		Item:          *NewItem(id, scope),
		id:            id,
		topPadding:    *vit.NewOptionalValue(vit.NewEmptyFloatValue()),
		rightPadding:  *vit.NewOptionalValue(vit.NewEmptyFloatValue()),
		bottomPadding: *vit.NewOptionalValue(vit.NewEmptyFloatValue()),
		leftPadding:   *vit.NewOptionalValue(vit.NewEmptyFloatValue()),
		padding:       *vit.NewEmptyFloatValue(),
		spacing:       *vit.NewEmptyFloatValue(),
		childLayouts:  make(vit.LayoutList),
	}
}

func (c *Column) String() string {
	return fmt.Sprintf("Column(%s)", c.id)
}

func (c *Column) Property(key string) (vit.Value, bool) {
	switch key {
	case "topPadding":
		return &c.topPadding, true
	case "rightPadding":
		return &c.rightPadding, true
	case "bottomPadding":
		return &c.bottomPadding, true
	case "leftPadding":
		return &c.leftPadding, true
	case "padding":
		return &c.padding, true
	case "spacing":
		return &c.spacing, true
	default:
		return c.Item.Property(key)
	}
}

func (c *Column) MustProperty(key string) vit.Value {
	v, ok := c.Property(key)
	if !ok {
		panic(fmt.Errorf("MustProperty called with unknown key %q", key))
	}
	return v
}

func (c *Column) SetProperty(key string, value interface{}) error {
	var err error
	switch key {
	case "topPadding":
		err = c.topPadding.SetValue(value)
	case "rightPadding":
		err = c.rightPadding.SetValue(value)
	case "bottomPadding":
		err = c.bottomPadding.SetValue(value)
	case "leftPadding":
		err = c.leftPadding.SetValue(value)
	case "padding":
		err = c.padding.SetValue(value)
	case "spacing":
		err = c.spacing.SetValue(value)
	default:
		return c.Item.SetProperty(key, value)
	}
	if err != nil {
		return vit.NewPropertyError("Column", key, c.id, err)
	}
	return nil
}

func (c *Column) SetPropertyExpression(key string, code string, pos *vit.PositionRange) error {
	switch key {
	case "topPadding":
		c.topPadding.SetExpression(code, pos)
	case "rightPadding":
		c.rightPadding.SetExpression(code, pos)
	case "bottomPadding":
		c.bottomPadding.SetExpression(code, pos)
	case "leftPadding":
		c.leftPadding.SetExpression(code, pos)
	case "padding":
		c.padding.SetExpression(code, pos)
	case "spacing":
		c.spacing.SetExpression(code, pos)
	default:
		return c.Item.SetPropertyExpression(key, code, pos)
	}
	return nil
}

func (c *Column) ResolveVariable(key string) (interface{}, bool) {
	switch key {
	case c.id:
		return c, true
	case "topPadding":
		return &c.topPadding, true
	case "rightPadding":
		return &c.rightPadding, true
	case "bottomPadding":
		return &c.bottomPadding, true
	case "leftPadding":
		return &c.leftPadding, true
	case "padding":
		return &c.padding, true
	case "spacing":
		return &c.spacing, true
	default:
		return c.Item.ResolveVariable(key)
	}
}

func (c *Column) AddChild(child vit.Component) {
	defer c.childWasAdded(child)
	child.SetParent(c)
	c.AddChildButKeepParent(child)
}

func (c *Column) AddChildAfter(afterThis vit.Component, addThis vit.Component) {
	defer c.childWasAdded(addThis)
	var targetType vit.Component = afterThis

	for ind, child := range c.Children() {
		if child.As(&targetType) {
			addThis.SetParent(c)
			c.AddChildAtButKeepParent(addThis, ind+1)
			return
		}
	}
	c.AddChild(addThis)
}

func (c *Column) UpdateExpressions() (int, vit.ErrorGroup) {
	var sum int
	var errs vit.ErrorGroup

	if changed, err := c.topPadding.Update(c); changed || err != nil {
		sum++
		if err != nil {
			errs.Add(vit.NewPropertyError("Column", "topPadding", c.id, err))
		}
		c.recalculateLayout(c.topPadding)
	}
	if changed, err := c.rightPadding.Update(c); changed || err != nil {
		sum++
		if err != nil {
			errs.Add(vit.NewPropertyError("Column", "rightPadding", c.id, err))
		}
		c.recalculateLayout(c.rightPadding)
	}
	if changed, err := c.bottomPadding.Update(c); changed || err != nil {
		sum++
		if err != nil {
			errs.Add(vit.NewPropertyError("Column", "bottomPadding", c.id, err))
		}
		c.recalculateLayout(c.bottomPadding)
	}
	if changed, err := c.leftPadding.Update(c); changed || err != nil {
		sum++
		if err != nil {
			errs.Add(vit.NewPropertyError("Column", "leftPadding", c.id, err))
		}
		c.recalculateLayout(c.leftPadding)
	}
	if changed, err := c.padding.Update(c); changed || err != nil {
		sum++
		if err != nil {
			errs.Add(vit.NewPropertyError("Column", "padding", c.id, err))
		}
		c.recalculateLayout(c.padding)
	}
	if changed, err := c.spacing.Update(c); changed || err != nil {
		sum++
		if err != nil {
			errs.Add(vit.NewPropertyError("Column", "spacing", c.id, err))
		}
		c.recalculateLayout(c.spacing)
	}
	if changed, err := c.childLayouts.Update(c); changed || err != nil {
		sum++
		if err != nil {
			errs.Add(vit.NewPropertyError("Column", "childLayouts", c.id, err))
		}
		c.recalculateLayout(c.childLayouts)
	}

	// this needs to be done in every component and not just in root to give the expression the highest level component for resolving variables
	n, err := c.UpdatePropertiesInContext(c)
	sum += n
	errs.AddGroup(err)
	n, err = c.Item.UpdateExpressions()
	sum += n
	errs.AddGroup(err)
	return sum, errs
}

func (c *Column) As(target *vit.Component) bool {
	if _, ok := (*target).(*Column); ok {
		*target = c
		return true
	}
	return c.Item.As(target)
}

func (c *Column) ID() string {
	return c.id
}

func (c *Column) Finish() error {
	return c.RootC().FinishInContext(c)
}
