// Code generated by vitrum gencmd. DO NOT EDIT.

package std

import (
	"fmt"
	vit "github.com/omniskop/vitrum/vit"
	parse "github.com/omniskop/vitrum/vit/parse"
)

func newFileContextForGradientStop(globalCtx *vit.GlobalContext) (*vit.FileContext, error) {
	return vit.NewFileContext(globalCtx), nil
}

type GradientStop struct {
	*Item
	id string

	position vit.FloatValue
	color    vit.ColorValue
}

// newGradientStopInGlobal creates an appropriate file context for the component and then returns a new GradientStop instance.
// The returned error will only be set if a library import that is required by the component fails.
func newGradientStopInGlobal(id string, globalCtx *vit.GlobalContext, thisLibrary parse.Library) (*GradientStop, error) {
	fileCtx, err := newFileContextForGradientStop(globalCtx)
	if err != nil {
		return nil, err
	}
	parse.AddLibraryToContainer(thisLibrary, &fileCtx.KnownComponents)
	return NewGradientStop(id, fileCtx), nil
}
func NewGradientStop(id string, context *vit.FileContext) *GradientStop {
	g := &GradientStop{
		Item:     NewItem("", context),
		id:       id,
		position: *vit.NewFloatValueFromCode(vit.Code{FileCtx: context, Code: "0.0", Position: nil}),
		color:    *vit.NewColorValueFromCode(vit.Code{FileCtx: context, Code: "\"transparent\"", Position: nil}),
	}
	// property assignments on embedded components
	// register listeners for when a property changes
	// register event listeners
	// register enumerations
	// add child components

	context.RegisterComponent("", g)

	return g
}

func (g *GradientStop) String() string {
	return fmt.Sprintf("GradientStop(%s)", g.id)
}

func (g *GradientStop) Property(key string) (vit.Value, bool) {
	switch key {
	case "position":
		return &g.position, true
	case "color":
		return &g.color, true
	default:
		return g.Item.Property(key)
	}
}

func (g *GradientStop) MustProperty(key string) vit.Value {
	v, ok := g.Property(key)
	if !ok {
		panic(fmt.Errorf("MustProperty called with unknown key %q", key))
	}
	return v
}

func (g *GradientStop) SetProperty(key string, value interface{}) error {
	var err error
	switch key {
	case "position":
		err = g.position.SetValue(value)
	case "color":
		err = g.color.SetValue(value)
	default:
		return g.Item.SetProperty(key, value)
	}
	if err != nil {
		return vit.NewPropertyError("GradientStop", key, g.id, err)
	}
	return nil
}

func (g *GradientStop) SetPropertyCode(key string, code vit.Code) error {
	switch key {
	case "position":
		g.position.SetCode(code)
	case "color":
		g.color.SetCode(code)
	default:
		return g.Item.SetPropertyCode(key, code)
	}
	return nil
}

func (g *GradientStop) Event(name string) (vit.Listenable, bool) {
	switch name {
	default:
		return g.Item.Event(name)
	}
}

func (g *GradientStop) ResolveVariable(key string) (interface{}, bool) {
	switch key {
	case "position":
		return &g.position, true
	case "color":
		return &g.color, true
	default:
		return g.Item.ResolveVariable(key)
	}
}

func (g *GradientStop) AddChild(child vit.Component) {
	child.SetParent(g)
	g.AddChildButKeepParent(child)
}

func (g *GradientStop) AddChildAfter(afterThis vit.Component, addThis vit.Component) {
	var targetType vit.Component = afterThis

	for ind, child := range g.Children() {
		if child.As(&targetType) {
			addThis.SetParent(g)
			g.AddChildAtButKeepParent(addThis, ind+1)
			return
		}
	}
	g.AddChild(addThis)
}

func (g *GradientStop) UpdateExpressions(context vit.Component) (int, vit.ErrorGroup) {
	var sum int
	var errs vit.ErrorGroup

	if context == nil {
		context = g
	}
	// properties
	if changed, err := g.position.Update(context); changed || err != nil {
		sum++
		if err != nil {
			errs.Add(vit.NewPropertyError("GradientStop", "position", g.id, err))
		}
	}
	if changed, err := g.color.Update(context); changed || err != nil {
		sum++
		if err != nil {
			errs.Add(vit.NewPropertyError("GradientStop", "color", g.id, err))
		}
	}

	// methods

	n, err := g.Item.UpdateExpressions(context)
	sum += n
	errs.AddGroup(err)
	return sum, errs
}

func (g *GradientStop) As(target *vit.Component) bool {
	if _, ok := (*target).(*GradientStop); ok {
		*target = g
		return true
	}
	return g.Item.As(target)
}

func (g *GradientStop) ID() string {
	return g.id
}

func (g *GradientStop) Finish() error {
	return g.RootC().FinishInContext(g)
}
