package gui

import "gioui.org/io/key"

var allSpecialKeys = []string{
	key.NameLeftArrow,
	key.NameRightArrow,
	key.NameUpArrow,
	key.NameDownArrow,
	key.NameReturn,
	key.NameEnter,
	key.NameEscape,
	key.NameHome,
	key.NameEnd,
	key.NameDeleteBackward,
	key.NameDeleteForward,
	key.NamePageUp,
	key.NamePageDown,
	key.NameTab,
	key.NameSpace,
	key.NameCtrl,
	key.NameShift,
	key.NameAlt,
	key.NameSuper,
	key.NameCommand,
	key.NameF1,
	key.NameF2,
	key.NameF3,
	key.NameF4,
	key.NameF5,
	key.NameF6,
	key.NameF7,
	key.NameF8,
	key.NameF9,
	key.NameF10,
	key.NameF11,
	key.NameF12,
	key.NameBack,
}

type KeyCode string

// maps gio key names to KeyboardEvent codes according to W3.
// https://www.w3.org/TR/uievents-code/#keyboard-key-codes
var keyCodeMapping = map[string]KeyCode{
	key.NameLeftArrow:      "ArrowLeft",
	key.NameRightArrow:     "ArrowRight",
	key.NameUpArrow:        "ArrowUp",
	key.NameDownArrow:      "ArrowDown",
	key.NameReturn:         "Enter",
	key.NameEnter:          "Enter",
	key.NameEscape:         "Escape",
	key.NameHome:           "Home",
	key.NameEnd:            "End",
	key.NameDeleteBackward: "Backspace",
	key.NameDeleteForward:  "Delete",
	key.NamePageUp:         "PageUp",
	key.NamePageDown:       "PageDown",
	key.NameTab:            "Tag",
	key.NameSpace:          "Space",
	key.NameCtrl:           "ControlLeft",
	key.NameShift:          "ShiftLeft",
	key.NameAlt:            "AltLeft",
	key.NameSuper:          "Super",
	key.NameCommand:        "MetaLeft",
	key.NameF1:             "F1",
	key.NameF2:             "F2",
	key.NameF3:             "F3",
	key.NameF4:             "F4",
	key.NameF5:             "F5",
	key.NameF6:             "F6",
	key.NameF7:             "F7",
	key.NameF8:             "F8",
	key.NameF9:             "F9",
	key.NameF10:            "F10",
	key.NameF11:            "F11",
	key.NameF12:            "F12",
	key.NameBack:           "BrowserBack",
}
